version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_APP=main.py
    networks:
      - default
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: flask run --host=0.0.0.0 --port=5000

  worker:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    volumes:
      - ./app:/app
    depends_on:
      - redis
    networks:
      - default
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command:
      - python
      - -c
      - |
        from worker import celery_app
        celery_app.worker_main(argv=['worker', '--loglevel=info', '--pool=threads'])

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - default

networks:
  default:
    driver: bridge
